# Generated by Django 6.0.7 on 2026-10-05 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def deactivate_legacy_consent(apps, schema_editor):
    consent_records = apps.get_model('monitoring', 'ConsentRecord')
    consent_records.objects.filter(session__isnull=True, active=True).update(active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consentrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='classrooms.classsession'),
        ),
        migrations.RunPython(deactivate_legacy_consent, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='emotionevent',
            name='label',
            field=models.CharField(choices=[('neutral_steady', 'Neutral / steady expression pattern'), ('positive_expression', 'Positive expression pattern'), ('negative_expression', 'Negative expression pattern'), ('surprise_like', 'Surprise-like expression pattern'), ('uncertain', 'Uncertain signal'), ('low_confidence', 'Low-confidence signal'), ('no_face', 'No face detected')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('student', 'session'), name='unique_student_session_consent'),
        ),
    ]
