# Generated by Django 5.2.17 on 2026-10-05 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('monitoring', '0002_alter_consentrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('on_track', 'Following comfortably'), ('another_example', 'Would like another example'), ('too_fast', 'The pace feels too fast'), ('need_pause', 'I need a short pause')], max_length=24)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='classrooms.classsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'response'], name='checkin_session_response_idx')],
            },
        ),
    ]
